### PR TITLE
Improved readability of text over images in tips scene

### PR DESCRIPTION
**Pull request by technimad**
Added a gradient over the image, which is darker where the text is over the images. This improves readability a lot especially for bright images.
Used the same gradient as used on npo.nl

### CODE REVIEW

**Comment by technimad** [comment]
turns out the gradient doesn't align properly yet. please do not merge until fixed.

**Comment by 4np** [comment]
Thanks for the contribution! I like the idea of adding a gradient as it _does_ sometimes get difficult to read the titles on the image, but it looks a bit weird with tvOS' focus engine. Perhaps it should be added as a subview of the image view with the anchors set to the bounds of the image view?

pasted_image_02_03_17_20_23

**Comment by 4np** [comment]
I am looking into an in-code solution, still the tvOS focus engine does not seem to [allow proper upscaling of the gradient layer](http://stackoverflow.com/questions/41853892/swift-how-to-add-a-layer-on-a-uiimageview-inside-of-a-uicollectionviewcell-and)...

screen shot 2017-03-02 at 20 56 13

**Comment by technimad** [comment]
yes, i also just noticed that issue when focus is on. Not found a solution yet.

**Comment by 4np** [comment]
I've solved the issue... 🙌🏻

**Pull request closed without merging**
